services:
  nodeweb:
    build:
      context: ./docker/nodeweb
      dockerfile: ./Dockerfile
    image: nodewebimage
    container_name: nodewebcontainer
    volumes:
      - ./:/app
    ports:
      # production
      - 8080:80
      # develop
      - 8081:81
    command: "run dev"
