services:
  nodeweb:
    build:
      context: ./docker/nodeweb
      dockerfile: ./Dockerfile
    image: nodewebimage
    container_name: nodewebcontainer
    volumes:
      - ./:/app
    ports:
      # develop
      - 8081:81
    command: "run dev"
    networks:
      - nodewebnetwork
  nodewebprd:
    build:
      context: ./docker/nodeweb
      dockerfile: ./Dockerfile
    image: nodewebimage
    container_name: nodewebprdcontainer
    volumes:
      - ./:/app
    ports:
      # production
      - 8080:80
    entrypoint: /bin/bash
    command: /app/run.sh
    networks:
      - nodewebnetwork
  vite:
    build:
      context: ./docker/vite
      dockerfile: ./Dockerfile
    image: viteimage
    container_name: vitecontainer
    volumes:
      - ./src/frontend:/app
    ports:
      - 5173:5173
    command: "run dev"
  mariadb:
    build:
      context: ./docker/mariadb
      dockerfile: ./Dockerfile
    image: mariadbimage
    container_name: mariadbcontainer
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    networks:
      - nodewebnetwork
networks:
  nodewebnetwork:
